#!/bin/bash

touch $HOME/.cargo/config
cp $HOME/.cargo/config $HOME/.cargo/config~

cat >> $HOME/.cargo/config <<EOF
[source]

[source.crates-io]
registry = 'https://github.com/rust-lang/crates.io-index'
replace-with = 'vendored-sources'

[source.vendored-sources]
directory = '$PWD/lambda_punter/vendor'
EOF

cd lambda_punter/

cargo build
RETVAL=$?
if [ $RETVAL -ne 0 ]; then
    echo "Build failed: $RETVAL"
    mv -f $HOME/.cargo/config~ $HOME/.cargo/config
    exit $RETVAL
fi

cargo test
RETVAL=$?
if [ $RETVAL -ne 0 ]; then
    echo "Test failed: $RETVAL"
    mv -f $HOME/.cargo/config~ $HOME/.cargo/config
    exit $RETVAL
fi

mv -f $HOME/.cargo/config~ $HOME/.cargo/config

exit 0
