[package]
name = "map_vis"
version = "0.1.1"
authors = ["Alexey Voznyuk <me@swizard.info>"]

[dependencies]
log = "0.3"
clap = "2.24"
env_logger = "0.4"
piston_window = "0.61"
serde = "1.0.8"
serde_json = "1.0"
serde_derive = "1.0"
lambda_punter = { path = "../lambda_punter" }
