[package]
name = "lambda_punter_online"
version = "0.1.2"
authors = ["Alexey Voznyuk <me@swizard.info>"]

[dependencies]
log = "0.3"
clap = "2.24"
env_logger = "0.4"
lambda_punter = { path = "../lambda_punter" }
